### PR TITLE
Fix StdioServerTransport.DisposeAsync hang

### LINKED ISSUE #221: ctrl-c doesn't cancel server on mac and linux
**Describe the bug**
After sending Ctrl-C to the console app, the server logs indicate that it is shutting down, but the process never exits requiring it to be killed.

Edit: I'm experiencing this on MacOS with SDK 9.0.100.  I haven't tried Windows or .Net 8.

**To Reproduce**

1. `dotnet new console`
2. `dotnet add package ModelContextProtocol --prerelease`
3. `dotnet add package Microsoft.Extensions.Hosting`
4. Copy code below into Program.cs and `dotnet run`

```csharp
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

var builder = Host.CreateApplicationBuilder(args);
builder.Logging.AddConsole(options => options.LogToStandardErrorThreshold = LogLevel.Trace);
builder.Services.AddMcpServer().WithStdioServerTransport();
await builder.Build().RunAsync();
```

**Expected behavior**

The app should completely shut down and exit after receiving a Ctrl-C signal.

**Logs**

```
info: ModelContextProtocol.Protocol.Transport.StdioServerTransport[728055718]
      Transport entering read messages loop for Server (stream) (mcp-server-shutdown)
info: ModelContextProtocol.Protocol.Transport.StdioServerTransport[625848173]
      Transport waiting for message for Server (stream) (mcp-server-shutdown)
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /Users/michael/Projects/mcp-server-shutdown
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
info: ModelContextProtocol.Server.McpServer[52599573]
      Endpoint message processing cancelled for Server (mcp-server-shutdown 1.0.0.0)
info: ModelContextProtocol.Server.McpServer[471153486]
      Cleaning up endpoint Server (mcp-server-shutdown 1.0.0.0)
info: ModelContextProtocol.Server.McpServer[883836513]
      Endpoint cleaned up for Server (mcp-server-shutdown 1.0.0.0)
info: ModelContextProtocol.Protocol.Transport.StdioServerTransport[156234308]
      Transport cleaning up for Server (stream) (mcp-server-shutdown)
```

### PR DESCRIPTION
**Pull request by halter73**
- It's not just Unix, it's all platforms that can hang
- Windows doesn't hang on Ctrl-C because that triggers the end of the Stream, but that doesn't help in IHostApplicationLifetime.StopAsync() scenarios

https://github.com/dotnet/runtime/blob/4e9627e311806330be72b7f7d3660be699878ebd/src/libraries/System.Console/src/System/ConsolePal.Unix.ConsoleStream.cs#L13 https://github.com/dotnet/runtime/blob/4e9627e311806330be72b7f7d3660be699878ebd/src/libraries/System.Console/src/System/ConsolePal.Windows.cs#L1149

Fixes #221

### CODE REVIEW

File: src/ModelContextProtocol/Protocol/Transport/StdioServerTransport.cs [hunk 1]
```diff
@@ -73,4 +73,32 @@ private static string GetServerName(McpServerOptions serverOptions)
 
         return serverOptions.ServerInfo?.Name ?? McpServer.DefaultImplementation.Name;
     }
+
+    // Neither WindowsConsoleStream nor UnixConsoleStream respect CancellationTokens or cancel any I/O on Dispose.
```
Comment (eiriktsarpalis) [inline src/ModelContextProtocol/Protocol/Transport/StdioServerTransport.cs:77]: I take it these are the platform-specific implementations from System.Console? Is there a bug we need to be reporting?

File: src/ModelContextProtocol/Protocol/Transport/StdioServerTransport.cs [hunk 2]
```diff
@@ -73,4 +73,32 @@ private static string GetServerName(McpServerOptions serverOptions)
...
+        public override bool CanRead => true;
+        public override bool CanSeek => false;
+        public override bool CanWrite => false;
+
+        public override Task<int> ReadAsync(byte[] buffer, int offset, int count, CancellationToken cancellationToken)
+            => stdinStream.ReadAsync(buffer, offset, count, cancellationToken).WaitAsync(cancellationToken);
+
+#if NET
+        public override ValueTask<int> ReadAsync(Memory<byte> buffer, CancellationToken cancellationToken = default)
+            => new(stdinStream.ReadAsync(buffer, cancellationToken).AsTask().WaitAsync(cancellationToken));
```
Comment (stephentoub) [inline src/ModelContextProtocol/Protocol/Transport/StdioServerTransport.cs:90]:
```suggestion
        public override ValueTask<int> ReadAsync(Memory<byte> buffer, CancellationToken cancellationToken = default)
        {
            ValueTask<int> vt = stdinStream.ReadAsync(buffer, cancellationToken);
            return vt.IsCompletedSuccessfully ? vt :  new(vt.AsTask().WaitAsync(cancellationToken));
        }
```

File: src/ModelContextProtocol/Protocol/Transport/StdioServerTransport.cs [hunk 3]
```diff
@@ -73,4 +73,32 @@ private static string GetServerName(McpServerOptions serverOptions)
...
+#endif
+
+        public override long Length => throw new NotSupportedException();
+
+        public override long Position { get => throw new NotSupportedException(); set => throw new NotSupportedException(); }
+
+        public override void Flush() => throw new NotSupportedException();
```
Comment (stephentoub) [inline src/ModelContextProtocol/Protocol/Transport/StdioServerTransport.cs:97]:
```suggestion
        public override void Flush() { }
```

File: src/ModelContextProtocol/Protocol/Transport/StdioServerTransport.cs [hunk 4]
```diff
@@ -73,4 +73,32 @@ private static string GetServerName(McpServerOptions serverOptions)
...
+    // Neither WindowsConsoleStream nor UnixConsoleStream respect CancellationTokens or cancel any I/O on Dispose.
+    // WindowsConsoleStream will return an EOS on Ctrl-C, but that is not the only reason the shutdownToken may fire.
+    private sealed class CancellableStdinStream(Stream stdinStream) : Stream
+    {
+        public override bool CanRead => true;
+        public override bool CanSeek => false;
+        public override bool CanWrite => false;
+
+        public override Task<int> ReadAsync(byte[] buffer, int offset, int count, CancellationToken cancellationToken)
+            => stdinStream.ReadAsync(buffer, offset, count, cancellationToken).WaitAsync(cancellationToken);
```
Comment (stephentoub) [inline src/ModelContextProtocol/Protocol/Transport/StdioServerTransport.cs:86]: These will not be recoverable, i.e. the actual read is not being canceled, just the wait, so if there's ever more data on the stream, the pending read will eat it, and any subsequent reads will miss that data.

We will need to ensure that cancellation tears down the server and this stream isn't used again.

File: src/ModelContextProtocol/Protocol/Transport/StdioServerTransport.cs (hunk 3 above)
Comment (halter73) [reply src/ModelContextProtocol/Protocol/Transport/StdioServerTransport.cs:97]: Is there a particular reason you expect the McpSerer to try to flush the stdin stream?

File: src/ModelContextProtocol/Protocol/Transport/StdioServerTransport.cs (hunk 1 above)
Comment (halter73) [reply src/ModelContextProtocol/Protocol/Transport/StdioServerTransport.cs:77]: I wasn't sure. Canceling a stdin read and then resuming it without exiting the process seemed like a niche scenario, so I wasn't going to raise a stink if we felt this workaround was good enough for tearing down the host and process, but it looks like @stephentoub is trying to make some improvements with https://github.com/dotnet/runtime/pull/114378.

File: src/ModelContextProtocol/Protocol/Transport/StdioServerTransport.cs (hunk 4 above)
Comment (halter73) [reply src/ModelContextProtocol/Protocol/Transport/StdioServerTransport.cs:86]: Agreed. That's why I limited this change to StdioServerTransport which typically is only disposed when tearing down the process and didn't make any changes to the base StreamServerTransport. Obviously, it'd be better if the stream returned by Console.OpenStandardInput() allowed cancelling the read operation propery in any manner, either with the token or by calling Dispose mid-operation, but neither of those things currently work.

File: src/ModelContextProtocol/Protocol/Transport/StdioServerTransport.cs (hunk 3 above)
Comment (stephentoub) [reply src/ModelContextProtocol/Protocol/Transport/StdioServerTransport.cs:97]: No, but if it does it shouldn't be an error. Flush on read streams is supposed to be a nop.
