### PR TITLE
SSE client transport: tolerate return of RPC responses in POST requests.

### LINKED ISSUE #439: Haystack Search MCP server fails from .NET client
**Describe the bug**

The Haystack Search MCP server works in VS Code and the MCP Inspector, but fails with the .NET MCP SDK:
(https://microsoft.visualstudio.com/Edge/_wiki/wikis/Edge.wiki/201379/Haystack-Search-Empower-your-search-in-VS-Code)

[Haystack Search - Empower your search in VS Code - Overview]

**To Reproduce**

1. Install the [VS Code extension](https://marketplace.visualstudio.com/items?itemName=codetrek.haystack-search)
1. [Add the MCP server](https://microsoft.visualstudio.com/Edge/_wiki/wikis/Edge.wiki/201379/Haystack-Search-Empower-your-search-in-VS-Code?anchor=integrate-with-github-copilot-(add-mcp-server-to-github-copilot)) to VS Code via its `http://localhost:13135/mcp/sse` endpoint.
2. Confirm that VS Code discovered 2 tools.
Image
3. Check out the MCP Inspector which also verifies two tools:
Image
4. Now try with the .NET MCP SDK:
```cs
var transport = new SseClientTransport(new SseClientTransportOptions { Endpoint = new Uri("http://localhost:13135/mcp/sse") });
IMcpClient client = await McpClientFactory.CreateAsync(transport)
```

Awaiting `CreateAsync` throws an exception

```
System.InvalidOperationException
  HResult=0x80131509
  Message=Failed to send message
  Source=ModelContextProtocol
  StackTrace:
   at ModelContextProtocol.Client.SseClientSessionTransport.<SendMessageAsync>d__10.MoveNext()
   at ModelContextProtocol.McpSession.<SendRequestAsync>d__28.MoveNext()
   at ModelContextProtocol.McpEndpointExtensions.<SendRequestAsync>d__1`2.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at ModelContextProtocol.Client.McpClient.<ConnectAsync>d__20.MoveNext()
   at ModelContextProtocol.Client.McpClient.<ConnectAsync>d__20.MoveNext()
   at ModelContextProtocol.Client.McpClientFactory.<CreateAsync>d__0.MoveNext()
   at ModelContextProtocol.Client.McpClientFactory.<CreateAsync>d__0.MoveNext()
   at Microsoft.VisualStudio.Conversations.Service.Mcp.McpServerTracker.<>c__DisplayClass8_0.<<-ctor>b__0>d.MoveNext() in Q:\source\VisualStudio.Conversations\src\Copilot.Service\Mcp\McpServerTracker.cs:line 57

  This exception was originally thrown at this call stack:
    ModelContextProtocol.Client.SseClientSessionTransport.SendMessageAsync(ModelContextProtocol.Protocol.JsonRpcMessage, System.Threading.CancellationToken)
    ModelContextProtocol.McpSession.SendRequestAsync(ModelContextProtocol.Protocol.JsonRpcRequest, System.Threading.CancellationToken)
    ModelContextProtocol.Client.McpClient.ConnectAsync(System.Threading.CancellationToken)
    ModelContextProtocol.Client.McpClient.ConnectAsync(System.Threading.CancellationToken)
    ModelContextProtocol.Client.McpClientFactory.CreateAsync(ModelContextProtocol.Client.IClientTransport, ModelContextProtocol.Client.McpClientOptions, Microsoft.Extensions.Logging.ILoggerFactory, System.Threading.CancellationToken)
    ModelContextProtocol.Client.McpClientFactory.CreateAsync(ModelContextProtocol.Client.IClientTransport, ModelContextProtocol.Client.McpClientOptions, Microsoft.Extensions.Logging.ILoggerFactory, System.Threading.CancellationToken)
    Microsoft.VisualStudio.Conversations.Service.Mcp.McpServerTracker..ctor.AnonymousMethod__0() in McpServerTracker.cs
```

**Expected behavior**

The connection succeeds. No exception thrown.

**Additional context**

Note this server is SSE -- Not "streamable HTTP". The Inspector fails when on "streamable HTTP". SSE mode seems to be the default for the .NET MCP SDK, so I expect this to work.

### PR DESCRIPTION
**Pull request by eiriktsarpalis**
Reinstates a piece of logic that tolerated the return of responses in the POST request itself. I've tweaked the heuristic somewhat so that it only falls back to that mode if the response content type is `application/json`. I have tested this against the impacted MCP server (Haystack Search) and validated that the fix works. cc @aarnott

Fix #439.

### CODE REVIEW

File: src/ModelContextProtocol/Client/SseClientSessionTransport.cs [hunk 1]
```diff
@@ -92,26 +92,25 @@ public override async Task SendMessageAsync(
...
             else
             {
                 LogRejectedPost(Name, messageId);
             }
 
-            throw new InvalidOperationException("Failed to send message");
+            response.EnsureSuccessStatusCode();
+        }
+
+        if (response.Content.Headers.ContentType?.MediaType is "application/json")
```
Comment (eiriktsarpalis) [inline src/ModelContextProtocol/Client/SseClientSessionTransport.cs:109]: Note that I've replaced the older heuristic (response content being empty or not "accepted") with a check against the media type.

File: src/ModelContextProtocol/Client/SseClientSessionTransport.cs [hunk 2]
```diff
@@ -92,26 +92,25 @@ public override async Task SendMessageAsync(
...
+        {
+            // Certain MCP servers implementing SSE may return the response in the current POST request instead of the SSE stream.
+            // Even though this is not officially part of the SSE protocol, we handle it here.
+            await ProcessInboundMessage(await response.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false), cancellationToken).ConfigureAwait(false);
```
Comment (halter73) [inline src/ModelContextProtocol/Client/SseClientSessionTransport.cs:113]:
```suggestion
```

Did you try this with the [Haystack Search MCP Server](https://marketplace.visualstudio.com/items?itemName=codetrek.haystack-search)? In my testing, it sends the exact same message over the SSE channel leading to a log message about an "unknown request ID" since there's no longer an entry in the _pendingRequests ConcurrentDictionary for the initialize request.

```
info: ModelContextProtocol.Client.McpClient[429065462]
      http://localhost:13135/mcp/sse received request for unknown request ID '1'.
```

I think we should do the simpler thing and just ignore the response body. At most, I'd log the content at a trace level. And I think we should update the ..._ServerReturningResponseInPostRequest_... test to replicate the Haystack behavior.

Comment (eiriktsarpalis) [reply src/ModelContextProtocol/Client/SseClientSessionTransport.cs:113]: > In my testing, it sends the exact same message over the SSE channel leading to a log message about an "unknown request ID"

I take it you ran the test server as opposed to the Haystack server? The former was incorrectly issuing responses for notifications which is what was triggering those logs.

FWIW I just downloaded an update to Haystack after which I have stopped seeing JSON messages appear in responses. I presume this was a bug that got fixed on their side.

Unless @PederHP objects then, I'm going to completely remove the response content handling like you suggested.

**Review by halter73 — APPROVED** [review]
