### PR TITLE
Fixes #248 - Add CultureInfo.InvariantCulture to string interpolation…

### LINKED ISSUE #248: WeatherTools Quickstart: GetForecast in Server not working in some Cultures / geos
**Describe the bug**
Because string interpolation in C# uses the current culture by default, it might insert commas instead of dots for decimals in some locales. If latitude or longitude contain decimal values, which they do, the URL "/points/..." [here](https://github.com/modelcontextprotocol/csharp-sdk/blob/0c502c43af2b3bc2e3ca96e85a6057eed18e3677/samples/QuickstartWeatherServer/Tools/WeatherTools.cs#L44) won’t match the expected format of the weather API when using a culture with a comma decimal separator (e.g. germany, france, ...). 

Using CultureInfo.InvariantCulture ensures the decimal separator is always . and prevents the URL from breaking.
**To Reproduce**
1. Set your system / tool to use one of the affected cultures (e.g. using `CultureInfo.CreateSpecificCulture("de-DE")`
2. build the server sample with the tool and invoke a GetForecast call
3. see it failing bc. it's now (made-up) `28,2` instead of `28.2` which ledas to an error response.

**Expected behavior**
The samples should work everywhere.

**Logs**
If applicable, add logs to help explain your problem.

**Additional context**
First raised [here](https://github.com/modelcontextprotocol/docs/issues/230) in the docs repo, and there was the idea to fix it via [this docs pr](https://github.com/modelcontextprotocol/docs/pull/228) (see comments). This was closed in favour of https://github.com/modelcontextprotocol/csharp-sdk/pull/134 (which seems to be upstream for the docs quickstart). I left a [comment](https://github.com/modelcontextprotocol/csharp-sdk/pull/134#issuecomment-2781129622) and was [asked](https://github.com/modelcontextprotocol/csharp-sdk/pull/134#issuecomment-2784899140) to create a follow up issue. This is the follow up issue.

### PR DESCRIPTION
**Pull request by DGuhr**
… for langitude and longitude so the sample works everywhere.

## Motivation and Context
see #248 

## How Has This Been Tested?
I tested it locally as there are no sample tests (yet) and I live in an affected Culture/Geo.

## Breaking Changes
-

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update

## Checklist

- [x] I have read the [MCP Documentation](https://modelcontextprotocol.io)
- [x] My code follows the repository's style guidelines
- [x] New and existing tests pass locally
- [x] I have added appropriate error handling
- [x] I have added or updated documentation as needed

### CODE REVIEW

**Comment by DGuhr** [comment]
cc @stvansolano - here's the accompanying PR for the asked-for followup I created in #248

File: samples/QuickstartWeatherServer/Tools/WeatherTools.cs [hunk 1]
```diff
@@ -41,7 +42,8 @@ public static async Task<string> GetForecast(
         [Description("Latitude of the location.")] double latitude,
         [Description("Longitude of the location.")] double longitude)
     {
-        using var jsonDocument = await client.ReadJsonDocumentAsync($"/points/{latitude},{longitude}");
+        var pointUrl = string.Format(CultureInfo.InvariantCulture, "points/{0},{1}", latitude, longitude);
```
Comment (stephentoub) [inline samples/QuickstartWeatherServer/Tools/WeatherTools.cs:45]:
```suggestion
        var pointUrl = string.Create(CultureInfo.InvariantCulture, $"/points/{latitude},{longitude}");
```
