### PR TITLE
Fix relative path resolution in sample app.

### LINKED ISSUE #395: QuickstartClient not working
Unhandled exception. System.InvalidOperationException: The server shut down unexpectedly.
   at ModelContextProtocol.Shared.McpSession.SendRequestAsync(JsonRpcRequest request, CancellationToken cancellationToken) in D:\02github\csharp-sdk\src\ModelContextProtocol\Shared\McpSession.cs:line 403
   at ModelContextProtocol.McpEndpointExtensions.SendRequestAsync[TParameters,TResult](IMcpEndpoint endpoint, String method, TParameters parameters, JsonTypeInfo`1 parametersTypeInfo, JsonTypeInfo`1 resultTypeInfo, RequestId requestId, CancellationToken cancellationToken) in D:\02github\csharp-sdk\src\ModelContextProtocol\McpEndpointExtensions.cs:line 91
   at ModelContextProtocol.Client.McpClient.ConnectAsync(CancellationToken cancellationToken) in D:\02github\csharp-sdk\src\ModelContextProtocol\Client\McpClient.cs:line 123
   at ModelContextProtocol.Client.McpClient.ConnectAsync(CancellationToken cancellationToken) in D:\02github\csharp-sdk\src\ModelContextProtocol\Client\McpClient.cs:line 169
   at ModelContextProtocol.Client.McpClientFactory.CreateAsync(IClientTransport clientTransport, McpClientOptions clientOptions, ILoggerFactory loggerFactory, CancellationToken cancellationToken) in D:\02github\csharp-sdk\src\ModelContextProtocol\Client\McpClientFactory.cs:line 39
   at ModelContextProtocol.Client.McpClientFactory.CreateAsync(IClientTransport clientTransport, McpClientOptions clientOptions, ILoggerFactory loggerFactory, CancellationToken cancellationToken) in D:\02github\csharp-sdk\src\ModelContextProtocol\Client\McpClientFactory.cs:line 48
   at Program.<Main>$(String[] args) in D:\02github\csharp-sdk\samples\QuickstartClient\Program.cs:line 23
   at Program.<Main>(String[] args)

D:\02github\csharp-sdk\artifacts\bin\QuickstartClient\Debug\net8.0\QuickstartClient.exe (process 39272) exited with code -532462766 (0xe0434352).
Press any key to close this window .

### PR DESCRIPTION
**Pull request by eiriktsarpalis**
Fix #395

### CODE REVIEW

File: samples/QuickstartClient/Program.cs [hunk 1]
```diff
@@ -89,6 +90,16 @@ static void PromptForInput()
...
         [var script] when script.EndsWith(".js") => ("node", args),
         [var script] when Directory.Exists(script) || (File.Exists(script) && script.EndsWith(".csproj")) => ("dotnet", ["run", "--project", script]),
-        _ => ("dotnet", ["run", "--project", "../QuickstartWeatherServer"])
+        _ => ("dotnet", ["run", "--project", Path.Combine(GetCurrentSourceDirectory(), "../QuickstartWeatherServer")])
     };
+}
+
+static string GetCurrentSourceDirectory([CallerFilePath] string? currentFile = null)
+{
+    if (string.IsNullOrWhiteSpace(currentFile))
```
Comment (stephentoub) [inline samples/QuickstartClient/Program.cs]: If this is null or whitespace, it's a compiler bug. If you really want to validate this, you could assert.

**Review by stephentoub — APPROVED** [review]

File: samples/QuickstartClient/Program.cs (hunk 1 above)
Comment (eiriktsarpalis) [reply samples/QuickstartClient/Program.cs]: Or the caller explicitly specifying a bogus parameter.

Comment (stephentoub) [reply samples/QuickstartClient/Program.cs]: Hence an assert.

File: samples/QuickstartClient/Program.cs [hunk 2]
```diff
@@ -89,6 +90,16 @@ static void PromptForInput()
...
+    {
+        throw new ArgumentException(nameof(currentFile));
+    }
```
Comment (eiriktsarpalis) [inline samples/QuickstartClient/Program.cs]:
```suggestion
    Debug.Assert(!string.IsNullOrWhiteSpace(currentFile));
```
